import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "./themeProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import ResponsiveLayout from "@/components/layout/resposniveLayout";

const outfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfitFont.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <MuiThemeProvider>
            <ResponsiveLayout />
            {children}
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
